######### USER SECTION ##########
# Redshift database under observation
redshift:
# URL of the Redshift Database. SSL not supported. Set `?ssl=false`|
  url: ""
# An admin user with access to all of Redshift system tables
  user: ""
# Password of admin user
  password: ""
# MySQL database where metrics will be stored.
mySql:
# URL of the MySQL Database. SSL not supprt. Set `useSSL=false`|
  url: ""
  user: ""
  password: ""

########## CRON SECTION ########################
# CRON attributes of various modules.
# Typically you do not need to edit this section
#################################################
#queryStatsCron:
#  frequencyMin: 60
#  delayMin: 5
#badQueriesCron:
#  frequencyMin: 60
#  delayMin: 5
#connectionsCron:
#  frequencyMin: 5
#  delayMin: 5

######## SYSTEM SECTION ########################
# Logging, metrics and Dropwizard configuration
# You should not need to edit this section.
################################################
logging:
  level: INFO
  loggers:
    io.inviscid: INFO
    io.inviscid.qan.Parser:
      level: ERROR
      additive: false
      appenders:
        - type: file
          currentLogFilename: /var/log/mart/sqlplanner.log
          archive: true
          archivedLogFilenamePattern: /var/log/mart/sqlplanner-%d.log
          archivedFileCount: 5
          timeZone: UTC
          immediateFlush: true
  appenders:
    - type: file
      currentLogFilename: /var/log/mart/server.log
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      archive: true
      archivedLogFilenamePattern: /var/log/mart/server-%d.log
      archivedFileCount: 5
      timeZone: UTC
      bufferSize: 8KB
      immediateFlush: true
server:
  requestLog:
    appenders:
    - type: file
      currentLogFilename: /var/log/mart/request.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/mart/request-%d.log
      archivedFileCount: 5
      timeZone: UTC
      immediateFlush: true
metrics:
  frequency: 1 minute
  reporters:
    - type: csv
      file: /var/log/mart/metrics
      includes:
        - inviscid.*
      useRegexFilters: true


